[profile.default]
solc_version = "0.8.21"
auto_detect_solc = false
optimizer = true
optimizer_runs = 1_000
gas_limit = 100_000_000 # ETH is 30M, but we use a higher value.
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
ffi = true

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 5_000

[profile.via-ir]
via_ir = true

[profile.via-ir.fuzz]
runs = 1_000

[profile.min-solc]
solc_version = "0.8.4"

[profile.min-solc.fuzz]
runs = 1_000

[profile.min-solc-via-ir]
via_ir = true
solc_version = "0.8.4"

[profile.min-solc-via-ir.fuzz]
runs = 1_000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config